# Generated by Django 2.1.5 on 2020-06-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191204_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='prior_hight_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
