# Generated by Django 2.1.5 on 2020-06-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_todoitem_prior_hight_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='prior_hight_count',
        ),
    ]
